# Functions: Graph Metadata {#fcns_g_metadata}



## `set_graph_name()`

<h4><em>Set graph name</em></h4>

<h5>DESCRIPTION</h5>

Set a name for a graph object of class `dgr_graph`.

<h5>PARAMETERS</h5>

**`graph`** a graph object of class `dgr_graph`.

**`name`** the name to set for the graph.

## `set_graph_time()`

<h4><em>Set graph date-time and timezone</em></h4>

<h5>DESCRIPTION</h5>

Set the time and timezone for a graph object of class `dgr_graph`.

<h5>PARAMETERS</h5>

**`graph`** a graph object of class `dgr_graph`.

**`time`** the date-time to set for the graph.

**`tz`** the timezone to set for the graph.

## `set_global_graph_attrs()`

<h4><em>Set global graph attributes</em></h4>

<h5>DESCRIPTION</h5>

Set global attributes of a specific type (either `graph_attrs`, `node_attrs`, or `edge_attrs` for a graph object of class `dgr_graph`).

<h5>PARAMETERS</h5>

**`graph`** a graph object of class `dgr_graph`.

**`attr`** the name of the attribute to set for the `type` of global attribute specified.

**`value`** the value to be set for the chosen attribute specified in the `attr_for_type` argument.

**`attr_type`** the specific type of global graph attribute to set. The type is specified with `graph`, `node`, or `edge`.

## `add_global_graph_attrs()`

<h4><em>Add one or more global graph attributes</em></h4>

<h5>DESCRIPTION</h5>

Add global attributes of a specific type (either `graph_attrs`, `node_attrs`, or `edge_attrs` for a graph object of class `dgr_graph`).

<h5>PARAMETERS</h5>

**`graph`** a graph object of class `dgr_graph`.

**`attr`** the name of the attribute to set for the `type` of global attribute specified.

**`value`** the value to be set for the chosen attribute specified in the `attr_for_type` argument.

**`attr_type`** the specific type of global graph attribute to set. The type is specified with `graph`, `node`, or `edge`.

## `get_global_graph_attrs()`

<h4><em>Get global graph attributes</em></h4>

<h5>DESCRIPTION</h5>

Get the presently set global attributes for a graph object of class `dgr_graph`.

<h5>PARAMETERS</h5>

**`graph`** a graph object of class `dgr_graph`.

## `delete_global_graph_attrs()`

<h4><em>Delete one of the global graph attributes stored within a graph object</em></h4>

<h5>DESCRIPTION</h5>

Delete one of the global attributes stored within a graph object of class `dgr_graph`).

<h5>PARAMETERS</h5>

**`graph`** a graph object of class `dgr_graph`.

**`attr`** the name of the attribute to delete for the `type` of global attribute specified.

**`attr_type`** the specific type of global graph attribute to delete. The type is specified with `graph`, `node`, or `edge`.

## `clear_global_graph_attrs()`

<h4><em>Clear any global graph attributes that are set</em></h4>

<h5>DESCRIPTION</h5>

Clear any currently set global graph attributes for a graph object of class `dgr_graph`).

<h5>PARAMETERS</h5>

**`graph`** a graph object of class `dgr_graph`.
